services:
  - type: web
    name: sst-sistema
    env: node
    plan: free
    buildCommand: npm run build:render
    startCommand: npm run preview
    envVars:
      - key: NODE_ENV
        value: production
    buildFilter:
      paths:
        - src/**
        - public/**
        - package.json
        - package-lock.json
        - vite.config.js
        - tailwind.config.js
        - postcss.config.js
